--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 750.0000, height = 1334.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(282)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(375.0000, 667.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1001.0000, height = 1334.0000})
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
Layer:addChild(Panel_1)

--Create pageView
local pageView = ccui.Layout:create()
pageView:ignoreContentAdaptWithSize(false)
pageView:setClippingEnabled(false)
pageView:setBackGroundColorType(1)
pageView:setBackGroundColor({r = 150, g = 200, b = 255})
pageView:setBackGroundColorOpacity(0)
pageView:setTouchEnabled(true);
pageView:setLayoutComponentEnabled(true)
pageView:setName("pageView")
pageView:setTag(163)
pageView:setCascadeColorEnabled(true)
pageView:setCascadeOpacityEnabled(true)
pageView:setAnchorPoint(0.5000, 0.5000)
pageView:setPosition(375.0000, 667.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(pageView)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1001.0000, height = 1334.0000})
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
Layer:addChild(pageView)

--Create btn_back
local btn_back = ccui.Button:create()
btn_back:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_back:loadTextureNormal("btn-common-back.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_back:loadTexturePressed("btn-common-back.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_back:loadTextureDisabled("btn-common-back.png",1)
btn_back:setTitleFontSize(14)
btn_back:setTitleColor({r = 65, g = 65, b = 70})
btn_back:setScale9Enabled(true)
btn_back:setCapInsets({x = 15, y = 11, width = 99, height = 60})
btn_back:setLayoutComponentEnabled(true)
btn_back:setName("btn_back")
btn_back:setTag(86)
btn_back:setCascadeColorEnabled(true)
btn_back:setCascadeOpacityEnabled(true)
btn_back:setPosition(81.5000, 89.0000)
btn_back.UserData = {}
btn_back.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btn_back:addClickEventListener(callBackProvider("olap_travel.lua", btn_back, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_back)
layout:setPositionPercentX(0.1087)
layout:setPositionPercentY(0.0667)
layout:setPercentWidth(0.1720)
layout:setPercentHeight(0.0615)
layout:setSize({width = 129.0000, height = 82.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(1)
layout:setLeftMargin(17.0000)
layout:setRightMargin(604.0000)
layout:setTopMargin(1204.0000)
layout:setBottomMargin(48.0000)
Layer:addChild(btn_back)

--Create btn_start
local btn_start = ccui.Button:create()
btn_start:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_start:loadTextureNormal("btn-299-96.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_start:loadTexturePressed("btn-299-96.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_start:loadTextureDisabled("btn-299-96.png",1)
btn_start:setTitleFontSize(14)
btn_start:setTitleColor({r = 65, g = 65, b = 70})
btn_start:setScale9Enabled(true)
btn_start:setCapInsets({x = 15, y = 11, width = 269, height = 74})
btn_start:setLayoutComponentEnabled(true)
btn_start:setName("btn_start")
btn_start:setTag(254)
btn_start:setCascadeColorEnabled(true)
btn_start:setCascadeOpacityEnabled(true)
btn_start:setPosition(370.3395, 286.9953)
btn_start.UserData = {}
btn_start.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btn_start:addClickEventListener(callBackProvider("olap_travel.lua", btn_start, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_start)
layout:setPositionPercentX(0.4938)
layout:setPositionPercentY(0.2151)
layout:setPercentWidth(0.3987)
layout:setPercentHeight(0.0720)
layout:setSize({width = 299.0000, height = 96.0000})
layout:setLeftMargin(220.8395)
layout:setRightMargin(230.1605)
layout:setTopMargin(999.0047)
layout:setBottomMargin(238.9953)
Layer:addChild(btn_start)

--Create Panel_2
local Panel_2 = ccui.Layout:create()
Panel_2:ignoreContentAdaptWithSize(false)
Panel_2:setClippingEnabled(false)
Panel_2:setBackGroundColorType(1)
Panel_2:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_2:setBackGroundColorOpacity(102)
Panel_2:setTouchEnabled(true);
Panel_2:setLayoutComponentEnabled(true)
Panel_2:setName("Panel_2")
Panel_2:setTag(255)
Panel_2:setCascadeColorEnabled(true)
Panel_2:setCascadeOpacityEnabled(true)
Panel_2:setPosition(149.5000, 48.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(149.5000)
layout:setRightMargin(149.5000)
layout:setTopMargin(48.0000)
layout:setBottomMargin(48.0000)
btn_start:addChild(Panel_2)

--Create LO_Start_2
local LO_Start_2 = ccui.Text:create()
LO_Start_2:ignoreContentAdaptWithSize(true)
LO_Start_2:setTextAreaSize({width = 0, height = 0})
LO_Start_2:setFontName("Resource/fonts/OverlapExt.ttf")
LO_Start_2:setFontSize(36)
LO_Start_2:setString([[start]])
LO_Start_2:setLayoutComponentEnabled(true)
LO_Start_2:setName("LO_Start_2")
LO_Start_2:setTag(256)
LO_Start_2:setCascadeColorEnabled(true)
LO_Start_2:setCascadeOpacityEnabled(true)
LO_Start_2:setTextColor({r = 242, g = 251, b = 254})
layout = ccui.LayoutComponent:bindLayoutComponent(LO_Start_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 95.0000, height = 42.0000})
layout:setLeftMargin(-47.5000)
layout:setRightMargin(-47.5000)
layout:setTopMargin(-21.0000)
layout:setBottomMargin(-21.0000)
Panel_2:addChild(LO_Start_2)

--Create LO_Start_1
local LO_Start_1 = ccui.Text:create()
LO_Start_1:ignoreContentAdaptWithSize(true)
LO_Start_1:setTextAreaSize({width = 0, height = 0})
LO_Start_1:setFontSize(36)
LO_Start_1:setString([[开始游戏]])
LO_Start_1:setLayoutComponentEnabled(true)
LO_Start_1:setName("LO_Start_1")
LO_Start_1:setTag(257)
LO_Start_1:setCascadeColorEnabled(true)
LO_Start_1:setCascadeOpacityEnabled(true)
LO_Start_1:setVisible(false)
layout = ccui.LayoutComponent:bindLayoutComponent(LO_Start_1)
layout:setSize({width = 144.0000, height = 42.0000})
layout:setLeftMargin(-72.0000)
layout:setRightMargin(-72.0000)
layout:setTopMargin(-21.0000)
layout:setBottomMargin(-21.0000)
Panel_2:addChild(LO_Start_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

