--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 750.0000, height = 1334.0000})

--Create Panel_3
local Panel_3 = ccui.Layout:create()
Panel_3:ignoreContentAdaptWithSize(false)
Panel_3:setClippingEnabled(false)
Panel_3:setBackGroundColorType(1)
Panel_3:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_3:setBackGroundColorOpacity(0)
Panel_3:setLayoutComponentEnabled(true)
Panel_3:setName("Panel_3")
Panel_3:setTag(201)
Panel_3:setCascadeColorEnabled(true)
Panel_3:setCascadeOpacityEnabled(true)
Panel_3:setAnchorPoint(0.5000, 0.5000)
Panel_3:setPosition(375.0000, 845.0117)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_3)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6334)
layout:setPercentWidth(0.9333)
layout:setPercentHeight(0.5592)
layout:setSize({width = 700.0000, height = 746.0000})
layout:setLeftMargin(25.0000)
layout:setRightMargin(25.0000)
layout:setTopMargin(115.9883)
layout:setBottomMargin(472.0117)
Layer:addChild(Panel_3)

--Create Sprite_6
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local Sprite_6 = cc.Sprite:createWithSpriteFrameName("sp-achieve-game-90.png")
Sprite_6:setName("Sprite_6")
Sprite_6:setTag(206)
Sprite_6:setCascadeColorEnabled(true)
Sprite_6:setCascadeOpacityEnabled(true)
Sprite_6:setPosition(92.5000, 653.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_6)
layout:setPositionPercentX(0.1321)
layout:setPositionPercentY(0.8760)
layout:setPercentWidth(0.0929)
layout:setPercentHeight(0.0871)
layout:setSize({width = 65.0000, height = 65.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(2)
layout:setLeftMargin(60.0000)
layout:setRightMargin(575.0000)
layout:setTopMargin(60.0000)
layout:setBottomMargin(621.0000)
Sprite_6:setBlendFunc({src = 1, dst = 771})
Panel_3:addChild(Sprite_6)

--Create Sprite_6_0
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local Sprite_6_0 = cc.Sprite:createWithSpriteFrameName("sp-achieve-game-90.png")
Sprite_6_0:setName("Sprite_6_0")
Sprite_6_0:setTag(207)
Sprite_6_0:setCascadeColorEnabled(true)
Sprite_6_0:setCascadeOpacityEnabled(true)
Sprite_6_0:setPosition(607.5000, 92.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_6_0)
layout:setPositionPercentX(0.8679)
layout:setPositionPercentY(0.1240)
layout:setPercentWidth(0.0929)
layout:setPercentHeight(0.0871)
layout:setSize({width = 65.0000, height = 65.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(1)
layout:setLeftMargin(575.0000)
layout:setRightMargin(60.0000)
layout:setTopMargin(621.0000)
layout:setBottomMargin(60.0000)
Sprite_6_0:setFlippedX(true)
Sprite_6_0:setFlippedY(true)
Sprite_6_0:setBlendFunc({src = 1, dst = 771})
Panel_3:addChild(Sprite_6_0)

--Create icon_red
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-home.plist")
local icon_red = cc.Sprite:createWithSpriteFrameName("main-icon-red.png")
icon_red:setName("icon_red")
icon_red:setTag(186)
icon_red:setCascadeColorEnabled(true)
icon_red:setCascadeOpacityEnabled(true)
icon_red:setPosition(637.5000, 683.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(icon_red)
layout:setPositionPercentX(0.9107)
layout:setPositionPercentY(0.9162)
layout:setPercentWidth(0.0357)
layout:setPercentHeight(0.0335)
layout:setSize({width = 25.0000, height = 25.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(625.0000)
layout:setRightMargin(50.0000)
layout:setTopMargin(50.0000)
layout:setBottomMargin(671.0000)
icon_red:setBlendFunc({src = 1, dst = 771})
Panel_3:addChild(icon_red)

--Create grid
local grid = ccui.Layout:create()
grid:ignoreContentAdaptWithSize(false)
grid:setClippingEnabled(false)
grid:setBackGroundColorType(1)
grid:setBackGroundColor({r = 255, g = 0, b = 0})
grid:setBackGroundColorOpacity(0)
grid:setLayoutComponentEnabled(true)
grid:setName("grid")
grid:setTag(200)
grid:setCascadeColorEnabled(true)
grid:setCascadeOpacityEnabled(true)
grid:setAnchorPoint(0.5000, 0.5000)
grid:setPosition(375.0000, 845.4996)
layout = ccui.LayoutComponent:bindLayoutComponent(grid)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6338)
layout:setPercentWidth(0.5493)
layout:setPercentHeight(0.3088)
layout:setSize({width = 412.0000, height = 412.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(169.0000)
layout:setRightMargin(169.0000)
layout:setTopMargin(282.5004)
layout:setBottomMargin(639.4996)
Layer:addChild(grid)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("game-bottom.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(40)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setAnchorPoint(0.5000, 0.0000)
Sprite_1:setPosition(375.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(0.3861)
layout:setSize({width = 1001.0000, height = 515.0000})
layout:setVerticalEdge(1)
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
layout:setTopMargin(819.0000)
Sprite_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(Sprite_1)

--Create optbackgrid
local optbackgrid = ccui.Layout:create()
optbackgrid:ignoreContentAdaptWithSize(false)
optbackgrid:setClippingEnabled(false)
optbackgrid:setBackGroundColorType(1)
optbackgrid:setBackGroundColor({r = 255, g = 0, b = 0})
optbackgrid:setBackGroundColorOpacity(0)
optbackgrid:setLayoutComponentEnabled(true)
optbackgrid:setName("optbackgrid")
optbackgrid:setTag(219)
optbackgrid:setCascadeColorEnabled(true)
optbackgrid:setCascadeOpacityEnabled(true)
optbackgrid:setAnchorPoint(0.5000, 0.0000)
optbackgrid:setPosition(375.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(optbackgrid)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(0.3748)
layout:setSize({width = 1001.0000, height = 500.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
layout:setTopMargin(834.0000)
Layer:addChild(optbackgrid)

--Create optgrid
local optgrid = ccui.Layout:create()
optgrid:ignoreContentAdaptWithSize(false)
optgrid:setClippingEnabled(false)
optgrid:setBackGroundColorType(1)
optgrid:setBackGroundColor({r = 255, g = 0, b = 0})
optgrid:setBackGroundColorOpacity(0)
optgrid:setLayoutComponentEnabled(true)
optgrid:setName("optgrid")
optgrid:setTag(218)
optgrid:setCascadeColorEnabled(true)
optgrid:setCascadeOpacityEnabled(true)
optgrid:setAnchorPoint(0.5000, 0.0000)
optgrid:setPosition(375.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(optgrid)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(0.3748)
layout:setSize({width = 1001.0000, height = 500.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
layout:setTopMargin(834.0000)
Layer:addChild(optgrid)

--Create btn_b
local btn_b = ccui.Button:create()
btn_b:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_b:loadTextureNormal("btn-134-87-n.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_b:loadTexturePressed("btn-129-79-h.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_b:loadTextureDisabled("btn-129-79-h.png",1)
btn_b:setTitleFontSize(14)
btn_b:setTitleColor({r = 65, g = 65, b = 70})
btn_b:setScale9Enabled(true)
btn_b:setCapInsets({x = 15, y = 11, width = 104, height = 65})
btn_b:setLayoutComponentEnabled(true)
btn_b:setName("btn_b")
btn_b:setTag(65)
btn_b:setCascadeColorEnabled(true)
btn_b:setCascadeOpacityEnabled(true)
btn_b:setPosition(175.3412, 679.3763)
if callBackProvider~=nil then
      btn_b:addClickEventListener(callBackProvider("olap_game.lua", btn_b, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_b)
layout:setPositionPercentX(0.2338)
layout:setPositionPercentY(0.5093)
layout:setPercentWidth(0.1787)
layout:setPercentHeight(0.0652)
layout:setSize({width = 134.0000, height = 87.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(1)
layout:setLeftMargin(108.3412)
layout:setRightMargin(507.6588)
layout:setTopMargin(611.1237)
layout:setBottomMargin(635.8763)
Layer:addChild(btn_b)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("label-btn-common-back.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(66)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(67.0000, 43.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2612)
layout:setPercentHeight(0.4023)
layout:setSize({width = 35.0000, height = 35.0000})
layout:setLeftMargin(49.5000)
layout:setRightMargin(49.5000)
layout:setTopMargin(26.0000)
layout:setBottomMargin(26.0000)
Sprite_1:setBlendFunc({src = 1, dst = 771})
btn_b:addChild(Sprite_1)

--Create btn_c
local btn_c = ccui.Button:create()
btn_c:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_c:loadTextureNormal("btn-134-87-n.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_c:loadTexturePressed("btn-129-79-h.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_c:loadTextureDisabled("btn-129-79-h.png",1)
btn_c:setTitleFontSize(14)
btn_c:setTitleColor({r = 65, g = 65, b = 70})
btn_c:setFlippedX(true)
btn_c:setScale9Enabled(true)
btn_c:setCapInsets({x = 15, y = 11, width = 104, height = 65})
btn_c:setLayoutComponentEnabled(true)
btn_c:setName("btn_c")
btn_c:setTag(67)
btn_c:setCascadeColorEnabled(true)
btn_c:setCascadeOpacityEnabled(true)
btn_c:setPosition(592.8813, 674.7363)
if callBackProvider~=nil then
      btn_c:addClickEventListener(callBackProvider("olap_game.lua", btn_c, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_c)
layout:setPositionPercentX(0.7905)
layout:setPositionPercentY(0.5058)
layout:setPercentWidth(0.1787)
layout:setPercentHeight(0.0652)
layout:setSize({width = 134.0000, height = 87.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(1)
layout:setLeftMargin(525.8813)
layout:setRightMargin(90.1187)
layout:setTopMargin(615.7637)
layout:setBottomMargin(631.2363)
Layer:addChild(btn_c)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("label-btn-common-back.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(68)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(67.0000, 43.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2612)
layout:setPercentHeight(0.4023)
layout:setSize({width = 35.0000, height = 35.0000})
layout:setLeftMargin(49.5000)
layout:setRightMargin(49.5000)
layout:setTopMargin(26.0000)
layout:setBottomMargin(26.0000)
Sprite_1:setBlendFunc({src = 1, dst = 771})
btn_c:addChild(Sprite_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(40)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(375.0000)
localFrame:setY(845.0117)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(375.0000)
localFrame:setY(845.0117)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(Panel_3)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(Panel_3)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(Panel_3)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(Panel_3)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(375.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(38)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(375.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(Sprite_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(38)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(Sprite_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(38)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(Sprite_1)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(38)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(Sprite_1)
--Create Animation List
local show = {name="show", startIndex=0, endIndex=40}
result['animation']:addAnimationInfo(show)

result['root'] = Layer
return result;
end

return Result

