--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 750.0000, height = 1334.0000})

--Create Panel_3
local Panel_3 = ccui.Layout:create()
Panel_3:ignoreContentAdaptWithSize(false)
Panel_3:setClippingEnabled(false)
Panel_3:setBackGroundColorType(1)
Panel_3:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_3:setBackGroundColorOpacity(0)
Panel_3:setLayoutComponentEnabled(true)
Panel_3:setName("Panel_3")
Panel_3:setTag(201)
Panel_3:setCascadeColorEnabled(true)
Panel_3:setCascadeOpacityEnabled(true)
Panel_3:setAnchorPoint(0.5000, 0.5000)
Panel_3:setPosition(375.0000, 845.0117)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_3)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6334)
layout:setPercentWidth(0.9333)
layout:setPercentHeight(0.5592)
layout:setSize({width = 700.0000, height = 746.0000})
layout:setLeftMargin(25.0000)
layout:setRightMargin(25.0000)
layout:setTopMargin(115.9883)
layout:setBottomMargin(472.0117)
Layer:addChild(Panel_3)

--Create grid
local grid = ccui.Layout:create()
grid:ignoreContentAdaptWithSize(false)
grid:setClippingEnabled(false)
grid:setBackGroundColorType(1)
grid:setBackGroundColor({r = 255, g = 0, b = 0})
grid:setBackGroundColorOpacity(0)
grid:setLayoutComponentEnabled(true)
grid:setName("grid")
grid:setTag(200)
grid:setCascadeColorEnabled(true)
grid:setCascadeOpacityEnabled(true)
grid:setAnchorPoint(0.5000, 0.5000)
grid:setPosition(375.0000, 845.4996)
layout = ccui.LayoutComponent:bindLayoutComponent(grid)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6338)
layout:setPercentWidth(0.5493)
layout:setPercentHeight(0.3088)
layout:setSize({width = 412.0000, height = 412.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(169.0000)
layout:setRightMargin(169.0000)
layout:setTopMargin(282.5004)
layout:setBottomMargin(639.4996)
Layer:addChild(grid)

--Create white
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local white = cc.Sprite:createWithSpriteFrameName("game-bottom.png")
white:setName("white")
white:setTag(40)
white:setCascadeColorEnabled(true)
white:setCascadeOpacityEnabled(true)
white:setAnchorPoint(0.5000, 0.0000)
white:setPosition(375.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(white)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(0.3861)
layout:setSize({width = 1001.0000, height = 515.0000})
layout:setVerticalEdge(1)
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
layout:setTopMargin(819.0000)
white:setBlendFunc({src = 1, dst = 771})
Layer:addChild(white)

--Create optbackgrid
local optbackgrid = ccui.Layout:create()
optbackgrid:ignoreContentAdaptWithSize(false)
optbackgrid:setClippingEnabled(false)
optbackgrid:setBackGroundColorType(1)
optbackgrid:setBackGroundColor({r = 255, g = 0, b = 0})
optbackgrid:setBackGroundColorOpacity(0)
optbackgrid:setLayoutComponentEnabled(true)
optbackgrid:setName("optbackgrid")
optbackgrid:setTag(219)
optbackgrid:setCascadeColorEnabled(true)
optbackgrid:setCascadeOpacityEnabled(true)
optbackgrid:setAnchorPoint(0.5000, 0.0000)
optbackgrid:setPosition(375.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(optbackgrid)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(0.3748)
layout:setSize({width = 1001.0000, height = 500.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
layout:setTopMargin(834.0000)
Layer:addChild(optbackgrid)

--Create optgrid
local optgrid = ccui.Layout:create()
optgrid:ignoreContentAdaptWithSize(false)
optgrid:setClippingEnabled(false)
optgrid:setBackGroundColorType(1)
optgrid:setBackGroundColor({r = 255, g = 0, b = 0})
optgrid:setBackGroundColorOpacity(0)
optgrid:setLayoutComponentEnabled(true)
optgrid:setName("optgrid")
optgrid:setTag(218)
optgrid:setCascadeColorEnabled(true)
optgrid:setCascadeOpacityEnabled(true)
optgrid:setAnchorPoint(0.5000, 0.0000)
optgrid:setPosition(373.9180, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(optgrid)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.4986)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(0.3748)
layout:setSize({width = 1001.0000, height = 500.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(-126.5820)
layout:setRightMargin(-124.4180)
layout:setTopMargin(834.0000)
Layer:addChild(optgrid)

--Create Panel_6
local Panel_6 = ccui.Layout:create()
Panel_6:ignoreContentAdaptWithSize(false)
Panel_6:setClippingEnabled(false)
Panel_6:setBackGroundColorType(1)
Panel_6:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_6:setBackGroundColorOpacity(0)
Panel_6:setLayoutComponentEnabled(true)
Panel_6:setName("Panel_6")
Panel_6:setTag(32)
Panel_6:setCascadeColorEnabled(true)
Panel_6:setCascadeOpacityEnabled(true)
Panel_6:setPosition(386.5419, 71.6749)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_6)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5154)
layout:setPositionPercentY(0.0537)
layout:setPercentWidth(0.2667)
layout:setPercentHeight(0.1499)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(386.5419)
layout:setRightMargin(163.4581)
layout:setTopMargin(1062.3250)
layout:setBottomMargin(71.6749)
Layer:addChild(Panel_6)

--Create LO_Touch_1
local LO_Touch_1 = ccui.Text:create()
LO_Touch_1:ignoreContentAdaptWithSize(true)
LO_Touch_1:setTextAreaSize({width = 0, height = 0})
LO_Touch_1:setFontSize(36)
LO_Touch_1:setString([[touch discovery]])
LO_Touch_1:setLayoutComponentEnabled(true)
LO_Touch_1:setName("LO_Touch_1")
LO_Touch_1:setTag(33)
LO_Touch_1:setCascadeColorEnabled(true)
LO_Touch_1:setCascadeOpacityEnabled(true)
LO_Touch_1:setVisible(false)
LO_Touch_1:setTextColor({r = 72, g = 76, b = 63})
layout = ccui.LayoutComponent:bindLayoutComponent(LO_Touch_1)
layout:setPercentWidth(1.2550)
layout:setPercentHeight(0.2100)
layout:setSize({width = 251.0000, height = 42.0000})
layout:setLeftMargin(-125.5000)
layout:setRightMargin(74.5000)
layout:setTopMargin(179.0000)
layout:setBottomMargin(-21.0000)
Panel_6:addChild(LO_Touch_1)

--Create LO_Touch_2
local LO_Touch_2 = ccui.Text:create()
LO_Touch_2:ignoreContentAdaptWithSize(true)
LO_Touch_2:setTextAreaSize({width = 0, height = 0})
LO_Touch_2:setFontName("Resource/fonts/Overlap.ttf")
LO_Touch_2:setFontSize(36)
LO_Touch_2:setString([[touch discovery]])
LO_Touch_2:setLayoutComponentEnabled(true)
LO_Touch_2:setName("LO_Touch_2")
LO_Touch_2:setTag(34)
LO_Touch_2:setCascadeColorEnabled(true)
LO_Touch_2:setCascadeOpacityEnabled(true)
LO_Touch_2:setTextColor({r = 72, g = 76, b = 63})
layout = ccui.LayoutComponent:bindLayoutComponent(LO_Touch_2)
layout:setPercentWidth(0.8700)
layout:setPercentHeight(0.2100)
layout:setSize({width = 174.0000, height = 42.0000})
layout:setLeftMargin(-87.0000)
layout:setRightMargin(113.0000)
layout:setTopMargin(179.0000)
layout:setBottomMargin(-21.0000)
Panel_6:addChild(LO_Touch_2)

--Create Sprite_8
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local Sprite_8 = cc.Sprite:createWithSpriteFrameName("game-touch-empty.png")
Sprite_8:setName("Sprite_8")
Sprite_8:setTag(86)
Sprite_8:setCascadeColorEnabled(true)
Sprite_8:setCascadeOpacityEnabled(true)
Sprite_8:setPosition(375.0000, 70.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_8)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0525)
layout:setPercentWidth(0.6307)
layout:setPercentHeight(0.0465)
layout:setSize({width = 473.0000, height = 62.0000})
layout:setLeftMargin(138.5000)
layout:setRightMargin(138.5000)
layout:setTopMargin(1233.0000)
layout:setBottomMargin(39.0000)
Sprite_8:setBlendFunc({src = 1, dst = 771})
Layer:addChild(Sprite_8)

--Create sb1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local sb1 = cc.Sprite:createWithSpriteFrameName("game-touch-half-1.png")
sb1:setName("sb1")
sb1:setTag(36)
sb1:setCascadeColorEnabled(true)
sb1:setCascadeOpacityEnabled(true)
sb1:setVisible(false)
sb1:setPosition(354.9900, 31.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sb1)
layout:setPositionPercentX(0.7505)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5011)
layout:setPercentHeight(1.0000)
layout:setSize({width = 237.0000, height = 62.0000})
layout:setLeftMargin(236.4900)
layout:setRightMargin(-0.4900)
sb1:setBlendFunc({src = 1, dst = 771})
Sprite_8:addChild(sb1)

--Create sb2
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local sb2 = cc.Sprite:createWithSpriteFrameName("game-touch-half-2.png")
sb2:setName("sb2")
sb2:setTag(37)
sb2:setCascadeColorEnabled(true)
sb2:setCascadeOpacityEnabled(true)
sb2:setVisible(false)
sb2:setPosition(118.2500, 31.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sb2)
layout:setPositionPercentX(0.2500)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5011)
layout:setPercentHeight(1.0000)
layout:setSize({width = 237.0000, height = 62.0000})
layout:setLeftMargin(-0.2500)
layout:setRightMargin(236.2500)
sb2:setBlendFunc({src = 1, dst = 771})
Sprite_8:addChild(sb2)

--Create btn_touch
local btn_touch = ccui.Button:create()
btn_touch:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
btn_touch:loadTextureNormal("game-touch-on.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
btn_touch:loadTexturePressed("game-touch-on.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
btn_touch:loadTextureDisabled("game-touch-on.png",1)
btn_touch:setTitleFontSize(14)
btn_touch:setTitleColor({r = 65, g = 65, b = 70})
btn_touch:setScale9Enabled(true)
btn_touch:setCapInsets({x = 30, y = 11, width = 1, height = 39})
btn_touch:setLayoutComponentEnabled(true)
btn_touch:setName("btn_touch")
btn_touch:setTag(35)
btn_touch:setCascadeColorEnabled(true)
btn_touch:setCascadeOpacityEnabled(true)
btn_touch:setPosition(236.5000, 31.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_touch)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentHeight(0.9839)
layout:setSize({width = 0.0000, height = 61.0000})
layout:setLeftMargin(236.5000)
layout:setRightMargin(236.5000)
layout:setTopMargin(0.5000)
layout:setBottomMargin(0.5000)
Sprite_8:addChild(btn_touch)

--Create btn_touch_0
local btn_touch_0 = ccui.Button:create()
btn_touch_0:ignoreContentAdaptWithSize(false)
btn_touch_0:loadTextureNormal("Resource/atlas/alpha.png",0)
btn_touch_0:loadTexturePressed("Resource/atlas/alpha.png",0)
btn_touch_0:loadTextureDisabled("Resource/atlas/alpha.png",0)
btn_touch_0:setTitleFontSize(14)
btn_touch_0:setTitleColor({r = 65, g = 65, b = 70})
btn_touch_0:setScale9Enabled(true)
btn_touch_0:setCapInsets({x = 0, y = 0, width = 1, height = 1})
btn_touch_0:setLayoutComponentEnabled(true)
btn_touch_0:setName("btn_touch_0")
btn_touch_0:setTag(65)
btn_touch_0:setCascadeColorEnabled(true)
btn_touch_0:setCascadeOpacityEnabled(true)
btn_touch_0:setPosition(235.9797, 30.5846)
if callBackProvider~=nil then
      btn_touch_0:addTouchEventListener(callBackProvider("olap_game.lua", btn_touch_0, "onTouch"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_touch_0)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.4989)
layout:setPositionPercentY(0.4933)
layout:setPercentWidth(0.9937)
layout:setPercentHeight(0.9677)
layout:setSize({width = 470.0000, height = 60.0000})
layout:setLeftMargin(0.9797)
layout:setRightMargin(2.0203)
layout:setTopMargin(1.4154)
layout:setBottomMargin(0.5846)
Sprite_8:addChild(btn_touch_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(40)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(375.0000)
localFrame:setY(845.0117)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(375.0000)
localFrame:setY(845.0117)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(Panel_3)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(Panel_3)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(Panel_3)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(Panel_3)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(375.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(38)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(375.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(white)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(38)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(white)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(38)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(white)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(38)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(white)
--Create Animation List
local show = {name="show", startIndex=0, endIndex=40}
result['animation']:addAnimationInfo(show)

result['root'] = Layer
return result;
end

return Result

