--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 750.0000, height = 1334.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(327)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(375.0000, 667.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1001.0000, height = 1334.0000})
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
Layer:addChild(Panel_1)

--Create scrollView
local scrollView = ccui.ScrollView:create()
scrollView:setBounceEnabled(true)
scrollView:setInnerContainerSize({width = 556, height = 450})
scrollView:ignoreContentAdaptWithSize(false)
scrollView:setClippingEnabled(false)
scrollView:setBackGroundColorOpacity(0)
scrollView:setLayoutComponentEnabled(true)
scrollView:setName("scrollView")
scrollView:setTag(13)
scrollView:setCascadeColorEnabled(true)
scrollView:setCascadeOpacityEnabled(true)
scrollView:setAnchorPoint(0.5000, 0.0000)
scrollView:setPosition(375.0000, 508.0084)
layout = ccui.LayoutComponent:bindLayoutComponent(scrollView)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3808)
layout:setPercentWidth(0.7413)
layout:setPercentHeight(0.3373)
layout:setSize({width = 556.0000, height = 450.0000})
layout:setLeftMargin(97.0000)
layout:setRightMargin(97.0000)
layout:setTopMargin(375.9916)
layout:setBottomMargin(508.0084)
Layer:addChild(scrollView)

--Create btn_ok
local btn_ok = ccui.Button:create()
btn_ok:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTextureNormal("btn-113-7.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTexturePressed("btn-113-7.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTextureDisabled("btn-113-7.png",1)
btn_ok:setTitleFontName("")
btn_ok:setTitleFontSize(48)
btn_ok:setTitleColor({r = 173, g = 216, b = 230})
btn_ok:setScale9Enabled(true)
btn_ok:setCapInsets({x = 15, y = 11, width = 83, height = 55})
btn_ok:setLayoutComponentEnabled(true)
btn_ok:setName("btn_ok")
btn_ok:setTag(167)
btn_ok:setCascadeColorEnabled(true)
btn_ok:setCascadeOpacityEnabled(true)
btn_ok:setPosition(371.9906, 398.8811)
btn_ok.UserData = {}
btn_ok.UserData[1] = [==========[sb]==========]
if callBackProvider~=nil then
      btn_ok:addClickEventListener(callBackProvider("home_lang.lua", btn_ok, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_ok)
layout:setPositionPercentX(0.4960)
layout:setPositionPercentY(0.2990)
layout:setPercentWidth(0.1507)
layout:setPercentHeight(0.0577)
layout:setSize({width = 113.0000, height = 77.0000})
layout:setHorizontalEdge(2)
layout:setLeftMargin(315.4906)
layout:setRightMargin(321.5094)
layout:setTopMargin(896.6189)
layout:setBottomMargin(360.3811)
Layer:addChild(btn_ok)

--Create Panel_2_0_0
local Panel_2_0_0 = ccui.Layout:create()
Panel_2_0_0:ignoreContentAdaptWithSize(false)
Panel_2_0_0:setClippingEnabled(false)
Panel_2_0_0:setBackGroundColorType(1)
Panel_2_0_0:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_2_0_0:setBackGroundColorOpacity(0)
Panel_2_0_0:setLayoutComponentEnabled(true)
Panel_2_0_0:setName("Panel_2_0_0")
Panel_2_0_0:setTag(168)
Panel_2_0_0:setCascadeColorEnabled(true)
Panel_2_0_0:setCascadeOpacityEnabled(true)
Panel_2_0_0:setAnchorPoint(0.5000, 0.5000)
Panel_2_0_0:setPosition(56.5000, 38.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2_0_0)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(56.5000)
layout:setRightMargin(56.5000)
layout:setTopMargin(38.5000)
layout:setBottomMargin(38.5000)
btn_ok:addChild(Panel_2_0_0)

--Create LO_OK_1
local LO_OK_1 = ccui.Text:create()
LO_OK_1:ignoreContentAdaptWithSize(true)
LO_OK_1:setTextAreaSize({width = 0, height = 0})
LO_OK_1:setFontSize(36)
LO_OK_1:setString([[OK]])
LO_OK_1:setLayoutComponentEnabled(true)
LO_OK_1:setName("LO_OK_1")
LO_OK_1:setTag(169)
LO_OK_1:setCascadeColorEnabled(true)
LO_OK_1:setCascadeOpacityEnabled(true)
LO_OK_1:setVisible(false)
layout = ccui.LayoutComponent:bindLayoutComponent(LO_OK_1)
layout:setSize({width = 53.0000, height = 42.0000})
layout:setLeftMargin(-26.5000)
layout:setRightMargin(-26.5000)
layout:setTopMargin(-21.0000)
layout:setBottomMargin(-21.0000)
Panel_2_0_0:addChild(LO_OK_1)

--Create LO_OK_2
local LO_OK_2 = ccui.Text:create()
LO_OK_2:ignoreContentAdaptWithSize(true)
LO_OK_2:setTextAreaSize({width = 0, height = 0})
LO_OK_2:setFontName("Resource/fonts/OverlapExt.ttf")
LO_OK_2:setFontSize(36)
LO_OK_2:setString([[OK]])
LO_OK_2:setLayoutComponentEnabled(true)
LO_OK_2:setName("LO_OK_2")
LO_OK_2:setTag(170)
LO_OK_2:setCascadeColorEnabled(true)
LO_OK_2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(LO_OK_2)
layout:setSize({width = 36.0000, height = 42.0000})
layout:setLeftMargin(-18.0000)
layout:setRightMargin(-18.0000)
layout:setTopMargin(-21.0000)
layout:setBottomMargin(-21.0000)
Panel_2_0_0:addChild(LO_OK_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

