--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 750.0000, height = 1334.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(249)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(375.0000, 667.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1001.0000, height = 1334.0000})
layout:setLeftMargin(-125.5000)
layout:setRightMargin(-125.5000)
Layer:addChild(Panel_1)

--Create Panel_1_0
local Panel_1_0 = ccui.Layout:create()
Panel_1_0:ignoreContentAdaptWithSize(false)
Panel_1_0:setClippingEnabled(false)
Panel_1_0:setBackGroundColorType(1)
Panel_1_0:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1_0:setBackGroundColorOpacity(0)
Panel_1_0:setTouchEnabled(true);
Panel_1_0:setLayoutComponentEnabled(true)
Panel_1_0:setName("Panel_1_0")
Panel_1_0:setTag(251)
Panel_1_0:setCascadeColorEnabled(true)
Panel_1_0:setCascadeOpacityEnabled(true)
Panel_1_0:setAnchorPoint(0.5000, 0.5000)
Panel_1_0:setPosition(384.9750, 658.6140)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1_0)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5133)
layout:setPositionPercentY(0.4937)
layout:setPercentWidth(1.3347)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1001.0000, height = 1334.0000})
layout:setLeftMargin(-115.5250)
layout:setRightMargin(-135.4750)
layout:setTopMargin(8.3860)
layout:setBottomMargin(-8.3860)
Layer:addChild(Panel_1_0)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
Image_1:loadTexture("common-dialog.png",1)
Image_1:setScale9Enabled(true)
Image_1:setCapInsets({x = 219, y = 129, width = 226, height = 135})
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(248)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(500.5000, 667.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6633)
layout:setPercentHeight(0.4280)
layout:setSize({width = 664.0000, height = 571.0000})
layout:setLeftMargin(168.5000)
layout:setRightMargin(168.5000)
layout:setTopMargin(381.5000)
layout:setBottomMargin(381.5000)
Panel_1_0:addChild(Image_1)

--Create btn_ok
local btn_ok = ccui.Button:create()
btn_ok:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTextureNormal("btn-134-87-n.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTexturePressed("btn-146-92-h.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
btn_ok:loadTextureDisabled("btn-146-92-h.png",1)
btn_ok:setTitleFontName("Resource/fonts/OverlapExt.ttf")
btn_ok:setTitleFontSize(48)
btn_ok:setTitleText("OK")
btn_ok:setTitleColor({r = 242, g = 251, b = 254})
btn_ok:setScale9Enabled(true)
btn_ok:setCapInsets({x = 15, y = 11, width = 104, height = 65})
btn_ok:setLayoutComponentEnabled(true)
btn_ok:setName("btn_ok")
btn_ok:setTag(250)
btn_ok:setCascadeColorEnabled(true)
btn_ok:setCascadeOpacityEnabled(true)
btn_ok:setPosition(493.5630, 483.6485)
if callBackProvider~=nil then
      btn_ok:addClickEventListener(callBackProvider("collection_info.lua", btn_ok, "onClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btn_ok)
layout:setPositionPercentX(0.4931)
layout:setPositionPercentY(0.3626)
layout:setPercentWidth(0.1339)
layout:setPercentHeight(0.0652)
layout:setSize({width = 134.0000, height = 87.0000})
layout:setLeftMargin(426.5630)
layout:setRightMargin(440.4370)
layout:setTopMargin(806.8515)
layout:setBottomMargin(440.1485)
Panel_1_0:addChild(btn_ok)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-home.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("collection-detail-1.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(6)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(503.3736, 743.8963)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentX(0.5029)
layout:setPositionPercentY(0.5576)
layout:setPercentWidth(0.1608)
layout:setPercentHeight(0.1297)
layout:setSize({width = 161.0000, height = 173.0000})
layout:setLeftMargin(422.8736)
layout:setRightMargin(417.1264)
layout:setTopMargin(503.6037)
layout:setBottomMargin(657.3963)
Sprite_1:setBlendFunc({src = 1, dst = 771})
Panel_1_0:addChild(Sprite_1)

--Create Panel_11
local Panel_11 = ccui.Layout:create()
Panel_11:ignoreContentAdaptWithSize(false)
Panel_11:setClippingEnabled(false)
Panel_11:setBackGroundColorType(1)
Panel_11:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_11:setBackGroundColorOpacity(0)
Panel_11:setLayoutComponentEnabled(true)
Panel_11:setName("Panel_11")
Panel_11:setTag(59)
Panel_11:setCascadeColorEnabled(true)
Panel_11:setCascadeOpacityEnabled(true)
Panel_11:setPosition(250.7536, 518.9166)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_11)
layout:setPositionPercentX(0.2505)
layout:setPositionPercentY(0.3890)
layout:setPercentWidth(0.4995)
layout:setPercentHeight(0.1124)
layout:setSize({width = 500.0000, height = 150.0000})
layout:setLeftMargin(250.7536)
layout:setRightMargin(250.2465)
layout:setTopMargin(665.0834)
layout:setBottomMargin(518.9166)
Panel_1_0:addChild(Panel_11)

--Create LO_info_1
local LO_info_1 = ccui.Text:create()
LO_info_1:ignoreContentAdaptWithSize(false)
LO_info_1:setFontName("")
LO_info_1:setFontSize(36)
LO_info_1:setString([[Text Label]])
LO_info_1:setTextHorizontalAlignment(1)
LO_info_1:setTextVerticalAlignment(1)
LO_info_1:setLayoutComponentEnabled(true)
LO_info_1:setName("LO_info_1")
LO_info_1:setTag(60)
LO_info_1:setCascadeColorEnabled(true)
LO_info_1:setCascadeOpacityEnabled(true)
LO_info_1:setPosition(221.6746, 68.9822)
LO_info_1:setTextColor({r = 118, g = 115, b = 113})
layout = ccui.LayoutComponent:bindLayoutComponent(LO_info_1)
layout:setPositionPercentX(0.4433)
layout:setPositionPercentY(0.4599)
layout:setPercentWidth(1.0400)
layout:setPercentHeight(1.0000)
layout:setSize({width = 520.0000, height = 150.0000})
layout:setLeftMargin(-38.3254)
layout:setRightMargin(18.3254)
layout:setTopMargin(6.0178)
layout:setBottomMargin(-6.0178)
Panel_11:addChild(LO_info_1)

--Create LO_info_2
local LO_info_2 = ccui.Text:create()
LO_info_2:ignoreContentAdaptWithSize(false)
LO_info_2:setFontName("Resource/fonts/Overlap.ttf")
LO_info_2:setFontSize(36)
LO_info_2:setString([[Text Label]])
LO_info_2:setTextHorizontalAlignment(1)
LO_info_2:setTextVerticalAlignment(1)
LO_info_2:setLayoutComponentEnabled(true)
LO_info_2:setName("LO_info_2")
LO_info_2:setTag(116)
LO_info_2:setCascadeColorEnabled(true)
LO_info_2:setCascadeOpacityEnabled(true)
LO_info_2:setPosition(229.8921, 62.5480)
LO_info_2:setTextColor({r = 118, g = 115, b = 113})
layout = ccui.LayoutComponent:bindLayoutComponent(LO_info_2)
layout:setPositionPercentX(0.4598)
layout:setPositionPercentY(0.4170)
layout:setPercentWidth(1.0400)
layout:setPercentHeight(1.0000)
layout:setSize({width = 520.0000, height = 150.0000})
layout:setLeftMargin(-30.1079)
layout:setRightMargin(10.1079)
layout:setTopMargin(12.4520)
layout:setBottomMargin(-12.4520)
Panel_11:addChild(LO_info_2)

--Create Panel_11_0
local Panel_11_0 = ccui.Layout:create()
Panel_11_0:ignoreContentAdaptWithSize(false)
Panel_11_0:setClippingEnabled(false)
Panel_11_0:setBackGroundColorType(1)
Panel_11_0:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_11_0:setBackGroundColorOpacity(0)
Panel_11_0:setTouchEnabled(true);
Panel_11_0:setLayoutComponentEnabled(true)
Panel_11_0:setName("Panel_11_0")
Panel_11_0:setTag(117)
Panel_11_0:setCascadeColorEnabled(true)
Panel_11_0:setCascadeOpacityEnabled(true)
Panel_11_0:setPosition(262.5366, 792.3816)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_11_0)
layout:setPositionPercentX(0.2623)
layout:setPositionPercentY(0.5940)
layout:setPercentWidth(0.4995)
layout:setPercentHeight(0.1124)
layout:setSize({width = 500.0000, height = 150.0000})
layout:setLeftMargin(262.5366)
layout:setRightMargin(238.4634)
layout:setTopMargin(391.6184)
layout:setBottomMargin(792.3816)
Panel_1_0:addChild(Panel_11_0)

--Create LO_Name_1
local LO_Name_1 = ccui.Text:create()
LO_Name_1:ignoreContentAdaptWithSize(true)
LO_Name_1:setTextAreaSize({width = 0, height = 0})
LO_Name_1:setFontName("")
LO_Name_1:setFontSize(36)
LO_Name_1:setString([[Text Label]])
LO_Name_1:setLayoutComponentEnabled(true)
LO_Name_1:setName("LO_Name_1")
LO_Name_1:setTag(118)
LO_Name_1:setCascadeColorEnabled(true)
LO_Name_1:setCascadeOpacityEnabled(true)
LO_Name_1:setPosition(221.6746, 68.9822)
LO_Name_1:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(LO_Name_1)
layout:setPositionPercentX(0.4433)
layout:setPositionPercentY(0.4599)
layout:setPercentWidth(0.3300)
layout:setPercentHeight(0.2800)
layout:setSize({width = 165.0000, height = 42.0000})
layout:setLeftMargin(139.1746)
layout:setRightMargin(195.8254)
layout:setTopMargin(60.0178)
layout:setBottomMargin(47.9822)
Panel_11_0:addChild(LO_Name_1)

--Create LO_Name_2
local LO_Name_2 = ccui.Text:create()
LO_Name_2:ignoreContentAdaptWithSize(true)
LO_Name_2:setTextAreaSize({width = 0, height = 0})
LO_Name_2:setFontName("Resource/fonts/OverlapExt.ttf")
LO_Name_2:setFontSize(36)
LO_Name_2:setString([[Text Label]])
LO_Name_2:setLayoutComponentEnabled(true)
LO_Name_2:setName("LO_Name_2")
LO_Name_2:setTag(119)
LO_Name_2:setCascadeColorEnabled(true)
LO_Name_2:setCascadeOpacityEnabled(true)
LO_Name_2:setPosition(229.8921, 62.5480)
LO_Name_2:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(LO_Name_2)
layout:setPositionPercentX(0.4598)
layout:setPositionPercentY(0.4170)
layout:setPercentWidth(0.3400)
layout:setPercentHeight(0.2800)
layout:setSize({width = 170.0000, height = 42.0000})
layout:setLeftMargin(144.8921)
layout:setRightMargin(185.1079)
layout:setTopMargin(66.4520)
layout:setBottomMargin(41.5480)
Panel_11_0:addChild(LO_Name_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(37)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(27)
localFrame:setX(384.9750)
localFrame:setY(656.9950)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(384.9750)
localFrame:setY(656.9950)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(37)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(384.9750)
localFrame:setY(658.6140)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(Panel_1_0)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(27)
localFrame:setScaleX(0.2000)
localFrame:setScaleY(0.2000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(Panel_1_0)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(27)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(Panel_1_0)
--Create Animation List
local enter = {name="enter", startIndex=0, endIndex=40}
result['animation']:addAnimationInfo(enter)

result['root'] = Layer
return result;
end

return Result

