--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(0)
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(102)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setAnchorPoint(0.5000, 0.5000)
panel:setPosition(96.0000, 71.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setSize({width = 192.0000, height = 143.0000})
layout:setRightMargin(-192.0000)
layout:setTopMargin(-143.0000)
Node:addChild(panel)

--Create back1
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-game.plist")
local back1 = cc.Sprite:createWithSpriteFrameName("sp-collection-back.png")
back1:setName("back1")
back1:setTag(3)
back1:setCascadeColorEnabled(true)
back1:setCascadeOpacityEnabled(true)
back1:setPosition(82.7241, 90.8678)
layout = ccui.LayoutComponent:bindLayoutComponent(back1)
layout:setPositionPercentX(0.4309)
layout:setPositionPercentY(0.6354)
layout:setPercentWidth(0.8594)
layout:setPercentHeight(0.7273)
layout:setSize({width = 165.0000, height = 104.0000})
layout:setLeftMargin(0.2241)
layout:setRightMargin(26.7759)
layout:setTopMargin(0.1322)
layout:setBottomMargin(38.8678)
back1:setBlendFunc({src = 1, dst = 771})
panel:addChild(back1)

--Create collect
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/scollct.plist")
local collect = cc.Sprite:createWithSpriteFrameName("s-collection-1.png")
collect:setName("collect")
collect:setTag(25)
collect:setCascadeColorEnabled(true)
collect:setCascadeOpacityEnabled(true)
collect:setPosition(80.9977, 52.9995)
layout = ccui.LayoutComponent:bindLayoutComponent(collect)
layout:setPositionPercentX(0.4909)
layout:setPositionPercentY(0.5096)
layout:setPercentWidth(0.7091)
layout:setPercentHeight(0.6827)
layout:setSize({width = 117.0000, height = 71.0000})
layout:setLeftMargin(22.4977)
layout:setRightMargin(25.5023)
layout:setTopMargin(15.5005)
layout:setBottomMargin(17.4995)
collect:setBlendFunc({src = 1, dst = 771})
back1:addChild(collect)

--Create back2
local back2 = ccui.ImageView:create()
back2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resource/atlas/ui-common.plist")
back2:loadTexture("dialog-back-white.png",1)
back2:setScale9Enabled(true)
back2:setCapInsets({x = 13, y = 13, width = 14, height = 14})
back2:setLayoutComponentEnabled(true)
back2:setName("back2")
back2:setTag(16)
back2:setCascadeColorEnabled(true)
back2:setCascadeOpacityEnabled(true)
back2:setPosition(81.8488, 91.4079)
back2:setOpacity(127)
layout = ccui.LayoutComponent:bindLayoutComponent(back2)
layout:setSize({width = 165.0000, height = 104.0000})
layout:setLeftMargin(-0.6512)
layout:setRightMargin(-164.3488)
layout:setTopMargin(-143.4079)
layout:setBottomMargin(39.4079)
Node:addChild(back2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(10)
result['animation']:setTimeSpeed(1.0000)

--Create CColorTimeline
local CColorTimeline = ccs.Timeline:create()

localFrame = ccs.ColorFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setColor({r = 255, g = 255, b = 255})
CColorTimeline:addFrame(localFrame)

result['animation']:addTimeline(CColorTimeline)
CColorTimeline:setNode(panel)
--Create Animation List

result['root'] = Node
return result;
end

return Result

